<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8W6wbel\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8W6wbel/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8W6wbel.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8W6wbel\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8W6wbel\App_KernelDevDebugContainer([
    'container.build_hash' => '8W6wbel',
    'container.build_id' => 'bd7b1807',
    'container.build_time' => 1706718016,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8W6wbel');
